baserow:
  base_url: "http://129.159.18.115:49161"
  api_token: "PfMJRl1I6CVwHPPLQ578vHmxvCR6fVMB"
  
  # The numeric ID of the new, unified Master Catalogue table
  master_catalogue_table_id: 726 # <-- UPDATED KEY AND VALUE

scraper:
  domain: "amazon.in"
  min_delay_seconds: 2.5
  max_delay_seconds: 5.5
  max_items_to_scrape: 15